// START User
export const TOGGLE_USER_IS_AUTHENTICATE: string =
  'TOGGLE_USER_IS_AUTHENTICATE';

export const LOGIN_USER_AS_BUSINESS: string = 'LOGIN_USER_AS_BUSINESS';

// END User

// START Global
export const TOGGLE_ACTIVE_ROUTE_NAME: string = 'TOGGLE_ACTIVE_ROUTE_NAME';
// END Global

// START Certificate
export const GET_PRODUCT_BY_ID_REQUEST: string = 'GET_PRODUCT_BY_ID_REQUEST';
export const GET_PRODUCT_BY_ID_SUCCESS: string = 'GET_PRODUCT_BY_ID_SUCCESS';
export const GET_PRODUCT_BY_ID_FAILURE: string = 'GET_PRODUCT_BY_ID_FAILURE';

export const SET_RISHE_CERTIFICATE_IN_OTHER_DEVICE: string =
  'SET_RISHE_CERTIFICATE_IN_OTHER_DEVICE';

export const GET_NAMAD_PRODUCT_BY_ID_REQUEST: string =
  'GET_NAMAD_PRODUCT_BY_ID_REQUEST';
export const GET_NAMAD_PRODUCT_BY_ID_SUCCESS: string =
  'GET_NAMAD_PRODUCT_BY_ID_SUCCESS';
export const GET_NAMAD_PRODUCT_BY_ID_FAILURE: string =
  'GET_NAMAD_PRODUCT_BY_ID_FAILURE';

export const SET_NAMAD_CERTIFICATE_IN_OTHER_DEVICE: string =
  'SET_NAMAD_CERTIFICATE_IN_OTHER_DEVICE';
// END Certificate
