export const APP: string = 'APP';

export const VERIFY: string = 'VERIFY';
export const LOGIN: string = 'LOGIN';

export const CERTIFICATE: string = 'CERTIFICATE';
export const CERTIFICATES: string = 'CERTIFICATES';

export const CHECK_CERTIFICATE: string = 'CHECK_CERTIFICATE';
export const REQUEST_PAYMENT_CERTIFICATE: string =
  'REQUEST_PAYMENT_CERTIFICATE';
export const GENERATE_CERTIFICATE: string = 'GENERATE_CERTIFICATE';
export const STATUS_CERTIFICATE: string = 'STATUS_CERTIFICATE';
export const PAYMENT_STATUS_CERTIFICATE: string = 'PAYMENT_STATUS_CERTIFICATE';
export const CERTIFICATE_DETAILS: string = 'CERTIFICATE_DETAILS';

export const CERTIFICATE_PAYMENT_HISTORIES: string =
  'CERTIFICATE_PAYMENT_HISTORIES';
export const REVOKE_CERTIFICATE: string = 'REVOKE_CERTIFICATE';

export const RISHE_CERTIFICATE_REQUEST_PAYMENT: string =
  'RISHE_CERTIFICATE_REQUEST_PAYMENT';

export const RISHE_CERTIFICATE_PAYMENT: string = 'RISHE_CERTIFICATE_PAYMENT';
export const RISHE_CERTIFICATE_GENERATE: string = 'RISHE_CERTIFICATE_GENERATE';
export const RISHE_CERTIFICATE_GENERATE_STATUS: string =
  'RISHE_CERTIFICATE_GENERATE_STATUS';
export const RISHE_CERTIFICATE_PAYMENT_HISTORY: string =
  'RISHE_CERTIFICATE_PAYMENT_HISTORY';

export const NAMAD_CERTIFICATE_REQUEST_PAYMENT: string =
  'NAMAD_CERTIFICATE_REQUEST_PAYMENT';

export const NAMAD_CERTIFICATE_PAYMENT: string = 'NAMAD_CERTIFICATE_PAYMENT';
export const NAMAD_CERTIFICATE_GENERATE: string = 'NAMAD_CERTIFICATE_GENERATE';
export const NAMAD_CERTIFICATE_GENERATE_STATUS: string =
  'NAMAD_CERTIFICATE_GENERATE_STATUS';
export const NAMAD_CERTIFICATE_PAYMENT_HISTORY: string =
  'NAMAD_CERTIFICATE_PAYMENT_HISTORY';

export const GENERATE_CERTIFICATE_DEEP_LINK: string =
  'GENERATE_CERTIFICATE_DEEP_LINK';

export const RULES_AND_CONDITIONS: string = 'Rules and conditions';
export const ENTER: string = 'Enter';

export const HOME: string = 'HOME';
export const DOCUMENTS: string = 'DOCUMENTS';
export const DOCUMENT_CREATED: string = 'DOCUMENT_CREATED';
export const DOCUMENT_RECEIVED: string = 'DOCUMENT_RECEIVED';
export const DOCUMENT_ARCHIVED: string = 'DOCUMENT_ARCHIVED';

export const CONTRACT: string = 'CONTRACT';
export const CONTRACT_DETAILS: string = 'CONTRACT_DETAILS';
export const CONTRACT_VALIDATION: string = 'CONTRACT_VALIDATION';
export const CONTRACT_NOT_VALID: string = 'CONTRACT_NOT_VALID';
export const CONTRACT_VALID: string = 'CONTRACT_VALID';
export const CREATE_CONTRACT: string = 'CREATE_CONTRACT';
export const CREATE_CONTRACT_SUCCESSFULLY: string =
  'CREATE_CONTRACT_SUCCESSFULLY';
export const CONTRACT_SIGN: string = 'CONTRACT_SIGN';
export const CONTRACT_REJECT: string = 'CONTRACT_REJECT';
export const CONTRACT_CANCELLATION: string = 'CONTRACT_CANCELLATION';

export const CREATE_CONTRACT_CONTACT_LIST: string =
  'CREATE_CONTRACT_CONTACT_LIST';

export const CONTACT_LIST: string = 'CONTACT_LIST';
export const CREATE_CONTACT: string = 'CREATE_CONTACT';
export const DEVICE_CONTACT_LIST: string = 'DEVICE_CONTACT_LIST';

export const PROFILE: string = 'PROFILE';

export const DRAFTS: string = 'DRAFTS';
export const CREATE_DOCUMENT_BY_DRAFT: string = 'CREATE_DOCUMENT_BY_DRAFT';
