import {StyleSheet} from 'react-native';
import colors from '../../../assets/theme/colors';

export default StyleSheet.create({
  wrapper: {flex: 1, paddingTop: 10},
  optionsWrapper: {
    paddingVertical: 12,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  optionTrashWrapper: {
    height: 46,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  selectedCountedText: {
    paddingLeft: 10,
    paddingHorizontal: 0,
    color: colors.primary.grayDark,
    fontSize: 15,
    fontFamily: 'YekanBakh-Bold',
    marginHorizontal: 6,
    marginTop: 4,
  },
  deleteContactText: {
    paddingHorizontal: 0,
    color: colors.primary.danger,
    fontSize: 15,
    fontFamily: 'YekanBakh-Bold',
    marginHorizontal: 6,
  },
  rejectText: {
    paddingHorizontal: 10,
    color: colors.primary.grayDark,
    fontSize: 15,
    fontFamily: 'YekanBakh-Bold',
    marginHorizontal: 6,
  },
  optionsTextWrapper: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  filter: {
    backgroundColor: colors.white,
    paddingHorizontal: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 1000,
  },
  optionsIconWrapper: {
    position: 'relative',
    zIndex: 1000,
  },
  optionsIcon: {
    transform: [{rotate: '90deg'}],
    paddingHorizontal: 5,
    color: colors.gray,
    marginTop: 6,
  },
  inputWrapper: {flexGrow: 1},
  filterInputLabel: {
    // backgroundColor: colors.lightGray,
  },
  filterInput: {
    width: '100%',
    textAlign: 'right',
    color: 'black',
  },
  filterInputWrapper: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    top: 0,
    right: 0,
    zIndex: 10,
  },
  contactCardWrapper: {
    backgroundColor: colors.white,
    borderRadius: 8,
    // shadowColor: '#d4d4d4',
    // shadowOffset: {width: 2, height: 2},
    // shadowOpacity: 1,
    // shadowRadius: 3,
    // elevation: 10,
    // padding: 6,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    marginBottom: 10,
    paddingVertical: 8,
    borderWidth: 1,
    borderStyle: 'solid',
    gap: 10,
  },
  contactCardInfoWrapper: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    flex: 1,
  },
  contactCardImgWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  contactCardInfoText: {
    color: colors.accent,
    fontFamily: 'YekanBakh-Bold',
    fontSize: 17,
    marginVertical: 5,
    textAlign: 'right',
    width: '100%',
  },
  contactCardPhoneText: {
    color: colors.primary.grayDark,
    fontFamily: 'YekanBakh-Bold',
    fontSize: 14,
    textAlign: 'right',
    width: '100%',
  },
  emptyListWrapper: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    height: 500,
  },
  emptyListText: {
    color: colors.primary.grayDark,
    fontFamily: 'YekanBakh-Bold',
    fontSize: 16,
    marginVertical: 5,
  },
  contactInfoModalDescription: {
    fontFamily: 'YekanBakh-Bold',
    fontSize: 15,
    color: colors.accent,
    textAlign: 'center',
    paddingBottom: 5,
  },
  error: {
    color: colors.primary.danger,
    fontFamily: 'YekanBakh-Bold',
    paddingTop: 4,
    fontSize: 12,
  },
});
