import {StyleSheet} from 'react-native';
import colors from '../../assets/theme/colors';

export default StyleSheet.create({
  wrapper: {},
  contractTitleWrapper: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  contractTitleType: {
    color: colors.accent,
    fontFamily: 'Vazir-Medium',
    fontSize: 14,
    marginBottom: 5,
  },
  contractTitleName: {
    color: colors.accent,
    fontFamily: 'YekanBakh-Bold',
    fontSize: 24,
  },
  contractTitleFooterWrapper: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  contractTitleFooterText: {
    color: colors.accent,
    fontFamily: 'Vazir-Medium',
    fontSize: 14,
    marginVertical: 5,
    marginHorizontal: 5,
  },
  contractTitleCompanyName: {
    color: colors.accent,
    fontFamily: 'YekanBakh-Bold',
    fontSize: 22,
  },
  acceptOrRejectContractWrapper: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 15,
  },
  acceptOrRejectContractText: {
    fontFamily: 'YekanBakh-Bold',
    fontSize: 15,
    paddingVertical: 10,
  },
  contractInformationWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 20,
  },
  contractInformationItem: {
    width: '33.3%',
    paddingHorizontal: 9,
  },
  contractInformationItemBorderStyle: {
    // borderRightWidth: 1,
    // borderLeftWidth: 1,
    borderColor: colors.secondary.paleGray,
    flexDirection: 'column',
    justifyContent: 'center',
    width: '100%',
    alignItems: 'center',
  },
  contractInformationItemText: {
    fontFamily: 'Vazir-Thin',
    fontSize: 14,
    color: colors.accent,
  },
  contractStatusWrapper: {
    paddingVertical: 15,
  },
  contractStatusTitle: {
    fontFamily: 'YekanBakh-Bold',
    fontSize: 16,
    color: colors.primary.grayDark,
  },
  contractStatusItemWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  contractStatusItemTitle: {
    fontFamily: 'YekanBakh-Bold',
    fontSize: 15,
    color: colors.accent,
  },
  contractStatusItemBadgeWrapper: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  contractStatusItemText: {
    fontFamily: 'Vazir-Thin',
    fontSize: 14,
    color: colors.primary.grayDark,
    paddingHorizontal: 10,
  },
  contractDescriptionWrapper: {
    marginTop: 10,
  },
  contractDescriptionTitle: {
    fontFamily: 'YekanBakh-Bold',
    fontSize: 16,
    color: colors.primary.grayDark,
    marginBottom: 10,
  },
  contractDescriptionText: {
    fontFamily: 'YekanBakh-Bold',
    fontSize: 15,
    color: colors.accent,
    textAlign: 'right',
  },
  buttonsGroup: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnWrapper: {
    width: '50%',
    padding: 10,
    // flexWrap: 'wrap',
  },
  receiptOfDocumentTitle: {
    fontFamily: 'YekanBakh-Bold',
    fontSize: 16,
    color: colors.primary.grayDark,
    marginBottom: 10,
  },
  receiptOfDocumentBox: {
    width: '100%',
    backgroundColor: colors.white,
    shadowColor: '#171717',
    shadowOffset: {width: 5, height: 5},
    shadowOpacity: 1,
    shadowRadius: 3,
    elevation: 5,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    height: 160,
    borderRadius: 6,
  },
  receiptOfDocumentImage: {},
  receiptOfDocumentText: {
    fontFamily: 'YekanBakh-Bold',
    fontSize: 16,
    color: colors.primary.gray,
    marginTop: 15,
  },
  footerWrapper: {
    paddingVertical: 20,
  },
  footerText: {
    fontFamily: 'YekanBakh-Bold',
    fontSize: 16,
    color: colors.primary.grayDark,
    marginTop: 15,
    textAlign: 'center',
    paddingHorizontal: 20,
  },
  savedFileAddressHintWrapper: {
    height: 60,
    width: '100%',
    backgroundColor: '#FFFBE6',
    position: 'absolute',
    zIndex: 100,
    bottom: 0,
    left: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 5,
  },
  savedFileAddressHintText: {
    fontFamily: 'YekanBakh-Bold',
    fontSize: 14,
    color: '#00091A',
    width: '90%',
  },
});
